# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xgw3_JblgPagqFgubYc3tqM7DkjcDewq
"""

# === ETAPA 1: PREPARAR OS DADOS ===
import pandas as pd
import numpy as np

df = pd.read_csv('merge_final.csv', sep=';', dtype=str, engine='python')

print("Quantidade de linhas e colunas:", df.shape)
print("\nNomes das colunas:")
print(df.columns.tolist())

display(df.head())

print("\nInformações gerais:")
print(df.info())

print("\nValores nulos por coluna (top 10):")
print(df.isnull().sum().sort_values(ascending=False).head(10))

# === ETAPA 2: SELECIONAR OS DADOS ===
import pandas as pd


try:
    df
except NameError:
    df = pd.read_csv('merge_final.csv', sep=';', dtype=str, engine='python')

print("Shape original:", df.shape)

cols_target = [

    'id','companyId','storeId','customerId',

    'createdAt','updatedAt','scheduledAt','sendAt','enrichedAt','dateOfBirth',

    'totalAmount','preparationTime','takeOutTimeInSeconds',


    'name','gender','phone','email','status'
]

cols_present = [c for c in cols_target if c in df.columns]
df_sel = df[cols_present].copy()

print("Colunas selecionadas:", cols_present)
print("Shape após seleção:", df_sel.shape)

display(df_sel.head(10))
print("\nNulos por coluna (top 10):")
print(df_sel.isnull().sum().sort_values(ascending=False).head(10))

df_sel.to_csv('merge_final_selected.csv', index=False)
print("\nArquivo gerado: merge_final_selected.csv")

# === ETAPA 3: LIMPAR / UNIFORMIZAR OS DADOS ===
import pandas as pd
import numpy as np

try:
    df_sel
except NameError:
    df_sel = pd.read_csv('merge_final_selected.csv', sep=',', dtype=str, engine='python')

print("Shape antes da limpeza:", df_sel.shape)

def to_snake(s: str) -> str:
    s = (
        s.strip()
         .replace('.', '_')
         .replace('-', '_')
         .replace(' ', '_')
         .replace('/', '_')
    )
    out = []
    for ch in s:
        out.append(('_' + ch.lower()) if ch.isupper() else ch)
    return ''.join(out).strip('_').lower()

df_clean = df_sel.copy()
df_clean.columns = [to_snake(c) for c in df_clean.columns]

for c in df_clean.columns:
    if df_clean[c].dtype == 'object':
        df_clean[c] = df_clean[c].astype(str).str.strip().replace({'nan': np.nan, 'None': np.nan, '': np.nan})


if 'id' in df_clean.columns:
    df_clean = df_clean.drop_duplicates(subset=['id'])
else:
    df_clean = df_clean.drop_duplicates()

date_cols = [c for c in df_clean.columns if c.endswith('_at') or ('date' in c)]
for c in date_cols:
    df_clean[c] = pd.to_datetime(df_clean[c], errors='coerce')

numeric_candidates = ['total_amount','preparation_time','take_out_time_in_seconds']
for c in df_clean.columns:
    if any(tok in c for tok in numeric_candidates):
        df_clean[c] = (
            df_clean[c].astype(str)
                        .str.replace('.', '', regex=False)   # remove milhar
                        .str.replace(',', '.', regex=False)  # vírgula → ponto
        )
        df_clean[c] = pd.to_numeric(df_clean[c], errors='coerce')

for c in df_clean.select_dtypes(include='number').columns:
    df_clean[c] = df_clean[c].fillna(0)

print("Shape após limpeza:", df_clean.shape)

display(df_clean.head(10))
print("\nInformações gerais:")
print(df_clean.info())
print("\nValores nulos por coluna (top 10):")
print(df_clean.isnull().sum().sort_values(ascending=False).head(10))

df_clean.to_csv('merge_final_clean.csv', index=False)
print("\nArquivo gerado: merge_final_clean.csv")

# === ETAPA 4: DERIVAR DADOS ===
import pandas as pd
import numpy as np

try:
    df_clean
except NameError:
    df_clean = pd.read_csv('merge_final_clean.csv')

print("Shape antes das derivações:", df_clean.shape)

df_der = df_clean.copy()


if {'preparation_time', 'take_out_time_in_seconds'}.issubset(df_der.columns):
    df_der['service_time_seconds'] = df_der['preparation_time'].fillna(0) + df_der['take_out_time_in_seconds'].fillna(0)
    print("✅ Coluna criada: service_time_seconds")


if 'total_amount' in df_der.columns and df_der['total_amount'].notna().any():
    q1, q2 = df_der['total_amount'].quantile([0.33, 0.66]).tolist()
    def bucket(v):
        if pd.isna(v): return 'desconhecido'
        if v <= q1: return 'baixo'
        if v <= q2: return 'medio'
        return 'alto'
    df_der['ticket_bucket'] = df_der['total_amount'].apply(bucket)
    print("✅ Coluna criada: ticket_bucket")

if 'date_of_birth' in df_der.columns:
    df_der['date_of_birth'] = pd.to_datetime(df_der['date_of_birth'], errors='coerce')
    today = pd.Timestamp('today').normalize()
    def calc_age(d):
        if pd.isna(d): return np.nan
        try:
            return int((today - d).days // 365.25)
        except Exception:
            return np.nan
    df_der['age'] = df_der['date_of_birth'].apply(calc_age)
    print("✅ Coluna criada: age")


print("\nShape após derivações:", df_der.shape)
display(df_der.head(10))

df_der.to_csv('merge_final_derived.csv', index=False)
print("\nArquivo gerado: merge_final_derived.csv")

# === ETAPA 5: INTEGRAR OS DADOS ===
import pandas as pd

try:
    df_der
except NameError:
    df_der = pd.read_csv('merge_final_derived.csv')

print("Shape base derivada:", df_der.shape)

dim_cols = [c for c in [
    'customer_id', 'gender', 'date_of_birth', 'phone', 'email', 'status', 'age'
] if c in df_der.columns]

if 'customer_id' in df_der.columns and dim_cols:
    dim_customer = (
        df_der[dim_cols]
        .drop_duplicates(subset=['customer_id'])
        .reset_index(drop=True)
    )

    rename_map = {c: f'customer__{c}' for c in dim_cols if c != 'customer_id'}
    dim_customer = dim_customer.rename(columns=rename_map)
else:
    dim_customer = pd.DataFrame()
    print("⚠️ Não foi possível criar dim_customer (coluna 'customer_id' ausente).")

print("Dim_customer shape:", dim_customer.shape)

fact = df_der.copy()
drop_from_fact = [c for c in dim_cols if c != 'customer_id']
fact = fact.drop(columns=drop_from_fact, errors='ignore')
print("Fact shape (antes do join):", fact.shape)


if not dim_customer.empty:
    fact_integrated = fact.merge(dim_customer, on='customer_id', how='left')
else:
    fact_integrated = fact.copy()

print("Fact_integrated shape:", fact_integrated.shape)

# 6) Amostras para validação
print("\nPrévia da dimensão de clientes:")
display(dim_customer.head(10))
print("\nPrévia da tabela de fatos integrada:")
display(fact_integrated.head(10))

# 7) Exportar outputs da etapa de integração
dim_customer.to_csv('dim_customer.csv', index=False)
fact.to_csv('fact_main.csv', index=False)                 # fato sem atributos de cliente
fact_integrated.to_csv('fact_integrated.csv', index=False)  # fato com atributos vindos da dimensão

print("\nArquivos gerados:")
print("- dim_customer.csv")
print("- fact_main.csv")
print("- fact_integrated.csv")

# === ETAPA 6: FORMATAR OS DADOS ===
import pandas as pd
import numpy as np

try:
    fact_integrated
    df_fmt = fact_integrated.copy()
    print("Base carregada da memória: fact_integrated")
except NameError:
    try:
        df_fmt = pd.read_csv('fact_integrated.csv')
        print("Base carregada do arquivo: fact_integrated.csv")
    except Exception:
        df_fmt = pd.read_csv('merge_final_derived.csv')
        print("Base carregada do arquivo: merge_final_derived.csv (fallback)")

print("Shape inicial:", df_fmt.shape)


date_cols = [c for c in df_fmt.columns if c.endswith('_at') or ('date' in c)]
for c in date_cols:
    df_fmt[c] = pd.to_datetime(df_fmt[c], errors='coerce')

numeric_candidates = ['total_amount','preparation_time','take_out_time_in_seconds','service_time_seconds','amount','price','value','count','quantity']
for c in df_fmt.columns:
    if any(tok in c for tok in numeric_candidates):

        if df_fmt[c].dtype == 'object':
            df_fmt[c] = (
                df_fmt[c].astype(str)
                          .str.replace('.', '', regex=False)
                          .str.replace(',', '.', regex=False)
            )
            df_fmt[c] = pd.to_numeric(df_fmt[c], errors='coerce')


if 'total_amount' in df_fmt.columns:
    df_fmt['total_amount'] = df_fmt['total_amount'].round(2)
for c in [col for col in df_fmt.select_dtypes(include='number').columns if col != 'total_amount']:
    df_fmt[c] = df_fmt[c].round(3)

id_cols = [c for c in df_fmt.columns if c == 'id' or c.endswith('_id')]
date_cols_fmt = [c for c in df_fmt.columns if (str(df_fmt[c].dtype).startswith('datetime64') or ('date' in c)) and c not in id_cols]
metric_cols = list(df_fmt.select_dtypes(include='number').columns)
cat_cols = [c for c in df_fmt.columns if c not in id_cols + date_cols_fmt + metric_cols]

prefer_order = [c for c in ['id','company_id','store_id','customer_id'] if c in id_cols]
id_cols = prefer_order + [c for c in id_cols if c not in prefer_order]

ordered_cols = [c for c in (id_cols + date_cols_fmt + metric_cols + cat_cols) if c in df_fmt.columns]
df_final = df_fmt[ordered_cols].copy()

sort_keys = [c for c in ['updated_at','created_at','scheduled_at','send_at'] if c in df_final.columns]
if sort_keys:
    df_final = df_final.sort_values(by=sort_keys, ascending=[False]*len(sort_keys))
out_name = 'merge_final_prepared.csv'
df_final.to_csv(out_name, index=False)

print("\nResumo da formatação:")
print("- Colunas (IDs):", id_cols)
print("- Colunas (Datas):", date_cols_fmt[:8], "..." if len(date_cols_fmt) > 8 else "")
print("- Colunas (Métricas):", metric_cols[:8], "..." if len(metric_cols) > 8 else "")
print(f"\nArquivo gerado: {out_name}")
print("Shape final:", df_final.shape)

# 7) Amostra final
display(df_final.head(10))